# Generated by Django 3.2.8 on 2022-04-06 23:23

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BoardInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_name', models.CharField(default='Room Name', max_length=30)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('type', models.CharField(default='basic', max_length=24)),
                ('resolution', models.CharField(default='1200x825', max_length=12)),
                ('isSetup', models.BooleanField(default=False)),
                ('refresh_rate', models.IntegerField(default=60)),
                ('s_message', models.CharField(blank=True, max_length=500)),
                ('d_message', models.CharField(blank=True, max_length=1000)),
                ('w_message', models.CharField(blank=True, max_length=2000)),
                ('message', models.CharField(blank=True, max_length=2000)),
                ('connection', models.BooleanField(default=False)),
                ('battery_status', models.CharField(default='100%', max_length=5)),
            ],
        ),
    ]
