# Generated by Django 3.2.8 on 2022-11-03 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20221103_1208'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='endDate',
            new_name='end',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='startDate',
            new_name='start',
        ),
    ]
