# Generated by Django 3.2.8 on 2022-11-05 18:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20221103_1246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='end',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 5, 12, 0, 46, 974053)),
        ),
        migrations.AlterField(
            model_name='event',
            name='start',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 5, 12, 0, 46, 974053)),
        ),
    ]
