# Generated by Django 3.2.8 on 2022-11-08 20:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_merge_20221108_1303'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admin',
            name='id',
        ),
        migrations.RemoveField(
            model_name='company',
            name='id',
        ),
        migrations.RemoveField(
            model_name='event',
            name='id',
        ),
        migrations.RemoveField(
            model_name='room',
            name='id',
        ),
        migrations.AddField(
            model_name='admin',
            name='user_id',
            field=models.TextField(default='u-1', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='company',
            name='comp_id',
            field=models.TextField(default='c-1', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='event',
            name='end',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 8, 13, 7, 0, 941854)),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_id',
            field=models.TextField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='event',
            name='start',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 8, 13, 7, 0, 941854)),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_id',
            field=models.TextField(primary_key=True, serialize=False),
        ),
    ]
