# Generated by Django 3.2.8 on 2022-11-02 19:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.TextField()),
                ('event_name', models.TextField()),
                ('event_desc', models.TextField()),
                ('startDate', models.DateField()),
                ('endDate', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_id', models.TextField()),
                ('room_num', models.IntegerField()),
                ('room_name', models.IntegerField()),
                ('location', models.TextField()),
                ('description', models.CharField(blank=True, max_length=1000)),
            ],
        ),
        migrations.RenameField(
            model_name='company',
            old_name='compId',
            new_name='comp_id',
        ),
        migrations.CreateModel(
            name='RoomAttributes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occupancy', models.IntegerField()),
                ('zoom_info', models.TextField()),
                ('availability', models.BooleanField()),
                ('req_approval', models.BooleanField(default=False)),
                ('room_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.room')),
            ],
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.TextField()),
                ('passW', models.TextField()),
                ('comp_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.company')),
            ],
        ),
    ]
