# Generated by Django 3.2.8 on 2022-11-03 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20221103_1158'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='event_desc',
            new_name='desc',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='event_name',
            new_name='title',
        ),
    ]
