# Generated by Django 3.2.8 on 2022-11-03 18:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20221103_1228'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='end',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 3, 12, 41, 21, 93675)),
        ),
        migrations.AddField(
            model_name='event',
            name='start',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 3, 12, 41, 21, 93675)),
        ),
    ]
