# Generated by Django 3.2.8 on 2022-11-08 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20221105_0225'),
        ('api', '0011_alter_event_end_alter_event_start'),
    ]

    operations = [
    ]
