# Generated by Django 4.1.3 on 2022-11-09 18:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20221108_1307'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='comp_id',
            new_name='compId',
        ),
        migrations.AlterField(
            model_name='event',
            name='end',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 9, 11, 21, 15, 968437)),
        ),
        migrations.AlterField(
            model_name='event',
            name='start',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 9, 11, 21, 15, 968437)),
        ),
    ]
