branch-defaults:
  default:
    environment: PREN-env
environment-defaults:
  PREN-env:
    branch: null
    repository: null
global:
  application_name: PREN
  default_ec2_keyname: aws-eb
  default_platform: Python 3.8 running on 64bit Amazon Linux 2
  default_region: us-west-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  sc: null
  workspace_type: Application
